package FileSystemApp;

/**
 * Holds a byte array in our corba object
 *
 * FileSystemApp/byteSeqHolder.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.2" from FileSystem.idl Thursday, November 10, 2016
 * 5:57:37 PM EST
 */

public final class byteSeqHolder implements org.omg.CORBA.portable.Streamable
{
	private byte value[] = null;

	/**
	 *
	 */
	public byteSeqHolder()
	{

	}
	/**
	 * @param initialValue the byte array we should hold
	 */
	public byteSeqHolder(byte[] initialValue)
	{
		value = initialValue;
	}

	/**
	 * @see org.omg.CORBA.portable.Streamable#_read(org.omg.CORBA.portable.InputStream)
	 */
	public void _read(org.omg.CORBA.portable.InputStream i)
	{
		value = FileSystemApp.byteSeqHelper.read(i);
	}

	/**
	 * @see org.omg.CORBA.portable.Streamable#_write(org.omg.CORBA.portable.OutputStream)
	 */
	public void _write(org.omg.CORBA.portable.OutputStream o)
	{
		FileSystemApp.byteSeqHelper.write(o, value);
	}

	/**
	 * @see org.omg.CORBA.portable.Streamable#_type()
	 */
	public org.omg.CORBA.TypeCode _type()
	{
		return FileSystemApp.byteSeqHelper.type();
	}

}
