package FileSystemApp;

/**
 * FileSystemApp/FileSystemOperations.java . Generated by the IDL-to-Java
 * compiler (portable), version "3.2" from FileSystem.idl Thursday, November 10,
 * 2016 5:57:37 PM EST
 */

public interface FileSystemOperations
{
	/**
	 * @return just get a string from the server to the client
	 */
	String sayHello();

	/**
	 * open a file on the server and dump its contents to the client
	 * @param title the title of the file
	 * @return the contents of the file
	 */
	String readFile(String title);

	/**
	 * make the server shut down
	 */
	void shutdown();
}
