package FileSystemApp;


/**
* FileSystemApp/FileCopy.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSystem.idl
* Monday, December 12, 2016 12:18:53 AM EST
*/

public final class FileCopy implements org.omg.CORBA.portable.IDLEntity
{
  public String fileContents = null;
  public boolean fileReturned = false;

  public FileCopy ()
  {
  } // ctor

  public FileCopy (String _fileContents, boolean _fileReturned)
  {
    fileContents = _fileContents;
    fileReturned = _fileReturned;
  } // ctor

} // class FileCopy
