package FileSystemApp;

/**
 * Holds a FileSystem object
 * FileSystemApp/FileSystemHolder.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.2" from FileSystem.idl Thursday, November 10, 2016
 * 5:57:37 PM EST
 *
 * Holds one FileSystem object
 */

public final class FileSystemHolder implements org.omg.CORBA.portable.Streamable
{
	private FileSystemApp.FileSystem value = null;

	/**
	 *
	 */
	public FileSystemHolder()
	{
	}

	/**
	 * @param initialValue the FileSystem object we should hold
	 */
	public FileSystemHolder(FileSystemApp.FileSystem initialValue)
	{
		value = initialValue;
	}

	/**
	 * @see org.omg.CORBA.portable.Streamable#_read(org.omg.CORBA.portable.InputStream)
	 */
	public void _read(org.omg.CORBA.portable.InputStream i)
	{
		value = FileSystemApp.FileSystemHelper.read(i);
	}

	/**
	 * @see org.omg.CORBA.portable.Streamable#_write(org.omg.CORBA.portable.OutputStream)
	 */
	public void _write(org.omg.CORBA.portable.OutputStream o)
	{
		FileSystemApp.FileSystemHelper.write(o, value);
	}

	/**
	 * @see org.omg.CORBA.portable.Streamable#_type()
	 */
	public org.omg.CORBA.TypeCode _type()
	{
		return FileSystemApp.FileSystemHelper.type();
	}

}
