package FileSystemApp;


/**
* FileSystemApp/fileListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSystem.idl
* Tuesday, December 6, 2016 6:39:22 PM EST
*/


// Typedefs //
public final class fileListHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public fileListHolder ()
  {
  }

  public fileListHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FileSystemApp.fileListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FileSystemApp.fileListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FileSystemApp.fileListHelper.type ();
  }

}
