package FileSystemApp;


/**
* FileSystemApp/FileSystemOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSystem.idl
* Tuesday, December 13, 2016 9:27:04 PM EST
*/

public interface FileSystemOperations 
{

  // Server-Server Functions //
  boolean hasFile (String fileName);
  FileSystemApp.FileCopy getFile (String fileName);
  boolean markDirty (String fileName);

  // Client-Server Functions //
  int openFileReadonly (String fileName);
  int openFileReadWrite (String fileName);
  String readRecord (int filePointer, int recordNumber);
  boolean writeRecord (int filePointer, int recordNumber, String newValue);
  void closeFile (int filePointer);

  // Testing Functions //
  String[] listFiles (boolean all);

  // System Functions //
  void shutdown ();
} // interface FileSystemOperations
