package FileSystemApp;


/**
* FileSystemApp/FileSystemPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSystem.idl
* Tuesday, December 6, 2016 6:39:22 PM EST
*/

public abstract class FileSystemPOA extends org.omg.PortableServer.Servant
 implements FileSystemApp.FileSystemOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("hasFile", new java.lang.Integer (0));
    _methods.put ("getFile", new java.lang.Integer (1));
    _methods.put ("openFileReadonly", new java.lang.Integer (2));
    _methods.put ("readRecord", new java.lang.Integer (3));
    _methods.put ("closeFile", new java.lang.Integer (4));
    _methods.put ("listOpenFiles", new java.lang.Integer (5));
    _methods.put ("listLocalFiles", new java.lang.Integer (6));
    _methods.put ("shutdown", new java.lang.Integer (7));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // Server-Server Functions //
       case 0:  // FileSystemApp/FileSystem/hasFile
       {
         String fileName = in.read_string ();
         boolean $result = false;
         $result = this.hasFile (fileName);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // FileSystemApp/FileSystem/getFile
       {
         String fileName = in.read_string ();
         String $result = null;
         $result = this.getFile (fileName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }


  // Client-Server Functions //
       case 2:  // FileSystemApp/FileSystem/openFileReadonly
       {
         String fileName = in.read_string ();
         int $result = (int)0;
         $result = this.openFileReadonly (fileName);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 3:  // FileSystemApp/FileSystem/readRecord
       {
         int lineNumber = in.read_long ();
         int filePointer = in.read_long ();
         String $result = null;
         $result = this.readRecord (lineNumber, filePointer);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // FileSystemApp/FileSystem/closeFile
       {
         int filePointer = in.read_long ();
         this.closeFile (filePointer);
         out = $rh.createReply();
         break;
       }


  // Testing Functions //
       case 5:  // FileSystemApp/FileSystem/listOpenFiles
       {
         String $result[] = null;
         $result = this.listOpenFiles ();
         out = $rh.createReply();
         FileSystemApp.fileListHelper.write (out, $result);
         break;
       }

       case 6:  // FileSystemApp/FileSystem/listLocalFiles
       {
         String $result[] = null;
         $result = this.listLocalFiles ();
         out = $rh.createReply();
         FileSystemApp.fileListHelper.write (out, $result);
         break;
       }


  // System Functions //
       case 7:  // FileSystemApp/FileSystem/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:FileSystemApp/FileSystem:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public FileSystem _this()
  {
    return FileSystemHelper.narrow(
    super._this_object());
  }

  public FileSystem _this(org.omg.CORBA.ORB orb)
  {
    return FileSystemHelper.narrow(
    super._this_object(orb));
  }


} // class FileSystemPOA
