package FileSystemApp;

/**
* FileSystemApp/fileCopyHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSystem.idl
* Sunday, December 11, 2016 11:25:48 PM EST
*/

public final class fileCopyHolder implements org.omg.CORBA.portable.Streamable
{
  public FileSystemApp.fileCopy value = null;

  public fileCopyHolder ()
  {
  }

  public fileCopyHolder (FileSystemApp.fileCopy initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FileSystemApp.fileCopyHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FileSystemApp.fileCopyHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FileSystemApp.fileCopyHelper.type ();
  }

}
